[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
H5Zzstd = "f6f2d980-1ec6-471c-a70d-0270e22f1103"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearInterpolations = "b20c7882-2490-4592-a606-fbbfe9e745e8"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Peaks = "18e31ff7-3703-566c-8e60-38913d67486b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QuackSim = "da450e9a-952d-45b1-babe-a413207209c2"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SignalAlignment = "00a43169-c78a-487b-af83-05d1ed4d9f28"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
SlurmClusterManager = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
SnoopCompileCore = "e2b509da-e806-4183-be48-004708413034"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[sources]
QuackSim = {rev = "1.0.5", url = "https://git.xfel.eu/machineLearning/quack-sim.git"}

[compat]
ADTypes = "1.11.0"
BenchmarkTools = "1.6.0"
CUDA = "5.6.0"
ClusterManagers = "2"
Clustering = "0.15"
Cthulhu = "2.16.0"
DSP = "0.8.0"
DataFrames = "1.7.0"
DataFramesMeta = "0.15.4"
DifferentialEquations = "7.15.0"
DifferentiationInterface = "0.7"
Distances = "0.10"
Distributions = "0.25"
DynamicQuantities = "1.4.0"
EllipsisNotation = "1.8.0"
Enzyme = "0.13.28"
FFTW = "1.8.0"
FiniteDiff = "2.26.2"
Format = "1"
ForwardDiff = "1"
H5Zzstd = "0.1.2"
HDF5 = "0.17.2"
IJulia = "1.26.0"
Interpolations = "0.16"
KernelAbstractions = "0.9.31"
LaTeXStrings = "1"
MPI = "0.20.22"
Measurements = "2.11.0"
MultivariateStats = "0.10"
NaNStatistics = "0.6.45"
Observables = "0.5.5"
OhMyThreads = "0.8"
Plots = "1.40.9"
ProgressMeter = "1.10.2"
PythonCall = "0.9.23"
ReadableRegex = "0.3.2"
Revise = "<3.13"
SQLite = "1.6.1"
SignalAlignment = "0.1"
SpecialFunctions = "2.5.0"
StatsBase = "0.34"
ThreadPinning = "1.0.2"
Tullio = "0.3.7"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
